import 'package:lockery_app/models/models.dart';

String jtwSecret = 'appoftwt';

List<LocationModel> locations = [
  LocationModel(id: 0, name: 'All'),
  LocationModel(id: 1, name: 'Colombo'),
  LocationModel(id: 2, name: 'Kandy'),
  LocationModel(id: 3, name: 'Bandarawela'),
  LocationModel(id: 4, name: 'Badulla'),
  LocationModel(id: 5, name: 'Nuwara Eliya'),
  LocationModel(id: 6, name: 'Jaffna'),
  LocationModel(id: 7, name: 'Negombo'),
  LocationModel(id: 8, name: 'Awissawella'),
  LocationModel(id: 9, name: 'Kurunegala'),
  LocationModel(id: 10, name: 'Wellawaya'),
];
// List<LockerModel> lockers = [
//   LockerModel(
//     lockerId: '1',
//     lockerName: 'Locker 01',
//     lockerLocation: locations[1],
//     bookedToken: '',
//     isAvailable: true,
//     isOpened: false,
//     isLocked: false,
//   ),
//   LockerModel(
//     lockerId: '2',
//     lockerName: 'Locker 02',
//     lockerLocation: locations[2],
//     bookedToken: '',
//     isAvailable: false,
//     isOpened: true,
//     isLocked: false,
//   ),
//   LockerModel(
//     lockerId: '3',
//     lockerName: 'Locker 03',
//     lockerLocation: locations[3],
//     bookedToken: '',
//     isAvailable: false,
//     isOpened: false,
//     isLocked: true,
//   ),
//   LockerModel(
//     lockerId: '4',
//     lockerName: 'Locker 04',
//     lockerLocation: locations[4],
//     bookedToken: '',
//     isAvailable: true,
//     isOpened: false,
//     isLocked: false,
//   ),
//   LockerModel(
//     lockerId: '4',
//     lockerName: 'Locker 04',
//     lockerLocation: locations[4],
//     bookedToken: '',
//     isAvailable: false,
//     isOpened: true,
//     isLocked: false,
//   ),
//   LockerModel(
//     lockerId: '5',
//     lockerName: 'Locker 05',
//     lockerLocation: locations[5],
//     bookedToken: '',
//     isAvailable: false,
//     isOpened: false,
//     isLocked: true,
//   ),
//   LockerModel(
//     lockerId: '6',
//     lockerName: 'Locker 06',
//     lockerLocation: locations[6],
//     bookedToken: '',
//     isAvailable: true,
//     isOpened: false,
//     isLocked: false,
//   ),
//   LockerModel(
//     lockerId: '7',
//     lockerName: 'Locker 07',
//     lockerLocation: locations[7],
//     bookedToken: '',
//     isAvailable: false,
//     isOpened: true,
//     isLocked: false,
//   ),
//   LockerModel(
//     lockerId: '8',
//     lockerName: 'Locker 08',
//     lockerLocation: locations[8],
//     bookedToken: '',
//     isAvailable: false,
//     isOpened: false,
//     isLocked: true,
//   ),
//   LockerModel(
//     lockerId: '9',
//     lockerName: 'Locker 09',
//     lockerLocation: locations[9],
//     bookedToken: '',
//     isAvailable: true,
//     isOpened: false,
//     isLocked: false,
//   ),
// ];
